---
- name: Learning about Template Module
  hosts: planetexpress
  gather_facts: yes

  vars:
          enginetype: darkmatter
          people: "Fry, Lela,Zoidberg"
          stuffincargo: Slurm Cola
          primarymission: Make a delievery of lsurm cola to the outer region of Perci Micron XII

  tasks:
          - name: build a template
            template:
                    src: template01.j2
                    dest: ~/ship.cfg
